### ISSUE TITLE
Cannot find module './onelogin/resources/users'

### ISSUE THREAD

**Issue by rahulpsd18** [onelogin/onelogin-node-sdk#13]
```
Error: Cannot find module './onelogin/resources/users'

Require stack:
- [PROJECT_LOCATION]\node_modules\@onelogin\sdk\dist\main.js
```
I checked the `dist/` folder and couldn't find the `resources/` folder that the main.js is trying to lookup. It's there in the `lib/` folder but not in `dist/`.

**Comment by dcaponi** [comment]
Hey @rahulpsd18 - Im really sorry this hung out for so long. I realize this is due to the way the code is being packaged (if you take a look, you'll notice there isnt really a good build step and half of the built code wasn't being tracked in git)

I made some fixes so now all the built code will be present in /dist which will resolve the error as of 2.0.10 (I also verified it works in one of my Svelte projects). 

I plan to add a better build system beyond `tsc` in the next rev. If you have any suggestions Im all ears.
